baseURL = "https://abanwar.com/"
title = "A.B. Anwar"
# theme
theme = "abanwar"
# post pagination
[pagination]
  pagerSize = 10
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
# googleAnalytics = "" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en

# disable language
disableLanguages = [""] # desable language from here

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[markup.goldmark.renderer]
    unsafe = true
[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 4
      noClasses = false

# footer links (menu)
[menu]

  [[menu.footer]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 10

  [[menu.footer]]
  name = "Terms of Service"
  url = "/terms/"
  weight = 20
