baseURL = "https://abanwar.com/"
title = "A.B. Anwar"

# theme
theme = "abanwar"

# post pagination
[pagination]
  pagerSize = 10

# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com

# google analytics
# googleAnalytics = "" # example: UA-123-45

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = false
  tabWidth = 4
  noClasses = false

# -------------------------------
# TAXONOMIES (CATEGORIES + TAGS)
# -------------------------------
[taxonomies]
  category = "categories"
  tag = "tags"

# -------------------------------
# PARAMS
# -------------------------------
[params]

  # ONLY these categories will appear
  # in the "Sections" dropdown
  sections_dropdown = [
    "Automation",
    "MacOS",
    "iOS",
    "Scripts",
    "Options Investing",
    "Miscellaneous",
    "Amazon affiliate"
  ]

# -------------------------------
# FOOTER LINKS (MENU)
# -------------------------------
[menu]

  [[menu.footer]]
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 10

  [[menu.footer]]
    name = "Terms of Service"
    url = "/terms/"
    weight = 20

  [[menu.footer]]
    name = "Sitemap"
    url = "/sitemap.xml"
    weight = 30
