[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about/"
weight = 2

[[main]]
name = "Services"
url = "/services/"
weight = 3

[[main]]
name = "Merchandise"
url = "https://bocciamans-store.creator-spring.com/?"
weight = 4
target = "_blank"  # Open in a new tab

# [[main]]
# name = "Inside That Ad"
# url = "https://www.insidethatad.net"
# weight = 5
# target = "_blank"  # Open in a new tab

# [[main]]
# name = "Subscribe"
# url = "/subscribe/"
# weight = 6

# [[main]]
# name = "DigitalStudioByAB"
# url = "https://www.etsy.com/shop/digitalstudiobyab"
# weight = 7
# target = "_blank"  # Open in a new tab

[[main]]
name = "Contact me"
url = "/contact/"
weight = 9

[[main]]
name = "YouTube"
url = "https://www.youtube.com/@AutomationMaestro"
weight = 10
target = "_blank"  # Open in a new tab